version: "3.7"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - local.env
    volumes:
      - ./video-subtitle-generator:/video-subtitle-generator
    ports:
      - "8422:8000"
    command: bash
